---
config:
  layout: elk
  theme: neutral
---
%%{ init: { 'themeVariables': { 'fontSize': '12px', 'fontFamily': 'Arial' } } }%%
classDiagram
    class Usuario {
        <<abstract>>
        - nome: string
        - empresa: string
        - email: string
        - cargo: string
        + comentar()
    }
    class Gerente {
        + listarEquipe()
        + listarProjetos()
        + listarTarefas()
    }
    class Colaborador {
        + concluirTarefa()
    }
    class Tarefa {
        - titulo: string
        - descricao: string
        - status: Status
        - urgencia: Urgencia
        - visibilidade: Visibilidade
        - dataCriacao: Date
        - dataPrazo: Date
    }
    class Projeto {
        - nome: string
        - descricao: string
        - dataCriacao: Date
        + listarTarefas()
        + listarMembros()
    }
    class Equipe {
        - descricao: string
        + adicionaMembro(Usuario)
    }
    class ConviteEquipe {
        - dataConvite: Date
        - dataVencimento: Date
        - mensagem: string
    }
    class Comentario {
        - mensagem: string
        - respostas: string[]
        - dataEnvio : Date
    }
    class Anexo {
        - pathArquivo: string
    }
    class Checklist {
        - titulo: string
    }
    class ItemChecklist {
        - descricao: string
        - concluido: bool
    }
    class Dashboard {
        + visualizarResumo()
    }
    class Lembrete {
        - mensagem: string
        - data: Date
    }
        class Status {
        <<enumeration>>
        ANDAMENTO
        ATRASADO
        CONCLUIDO_PRAZO
        CONCLUIDO_ATRASO
    }
    class Urgencia{
        <<enumeration>>
        CRITICO
        ALTO
        MODERADO
        BAIXO
    }
    class Visibilidade{
        <<enumeration>>
        PUBLICO
        APENAS_EQUIPE
        APENAS_GERENTE
        PRIVADO
    }
    Usuario <|-- Gerente
    Usuario <|-- Colaborador
    Usuario "* membros" <--> "* equipes" Equipe
    Usuario "1" *--> "1 dashboard" Dashboard
    Gerente "1 gerente" <--> "* projetos" Projeto
    Colaborador "* colaboradores" <--> "* tarefas" Tarefa
    Tarefa "1 tarefa" <--> "* comentarios" Comentario
    Tarefa "1" --> "* anexos" Anexo
    Tarefa "1" --> "1 checklist" Checklist
    Projeto "1" --> "* tarefas" Tarefa
    Projeto "1" --> "* comentarios" Comentario
    Projeto "1" --> "* anexos" Anexo
    Projeto ..> Equipe
    Equipe "1" ..> "1" Gerente
    Equipe "1" o--> "* membros" Usuario
    ConviteEquipe "1" ..> "1 usuario" Usuario
    ConviteEquipe "1" ..> "1 equipe" Equipe
    Comentario "*"..> "1 autor" Usuario
    Checklist "1" *--> "* itens" ItemChecklist
    Lembrete "1" ..> "1 tarefa" Tarefa